[tool.black]
line-length = 100
exclude = "features/steps/"
force_exclude = "venv/"


[tool.coverage.run]
omit = ["venv/*"]
branch = true

[mypy]
python_version = 3.10
warn_unused_configs = true
exclude = "features/.*"
plugins = ["behave.plugin"]
