name: Code coverage with coverage package

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0
      - name: Install dependencies
        run: |
          pip3.10 install -r requirements.txt
      - name: Generate code coverage report
        run: |
          coverage run -m behave
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
