name: Static Type Checking with mypy

on: [push, pull_request]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0
      - name: Install dependencies
        run: |
          pip3.10 install mypy
      - name: Typecheck with mypy
        run: |
          python3.10 -m mypy .
