name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        pip3.10 install -r requirements.txt
    - name: Typecheck with mypy
      run: |
        python3.10 -m mypy .
    - name: Test with behave
      run: |
        python3.10 -m behave
    - name: Test with mutatest
      run: |
        python3.10 -m mutatest
    - name: Generate code coverage report
      run: |
        coverage -m behave
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
